spring:
  profile.active: local

  datasource:
    url: jdbc:mysql://localhost:3306/AuditDB
    username: root
    password: password
    jpa:
      show-sql: true
      hibernate:
      ddl-auto: update